Document: raspbed
Title: Debian raspbed Manual
Author: <insert document author here>
Abstract: This manual describes what raspbed is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/raspbed/raspbed.sgml.gz

Format: postscript
Files: /usr/share/doc/raspbed/raspbed.ps.gz

Format: text
Files: /usr/share/doc/raspbed/raspbed.text.gz

Format: HTML
Index: /usr/share/doc/raspbed/html/index.html
Files: /usr/share/doc/raspbed/html/*.html
