QRaspbed: Bed Class Reference
Bed Class Reference
#include <Bed.hpp>
Classes
struct Relay
The Relay struct.
Public Member Functions
Bed ()
Bed Default bed constructor.
virtual ~Bed ()
void command (const char relay, bool on)
command
std::shared_ptr< SerialPort > getSerialPort ()
Public Attributes
struct Bed::Relay relay
Private Attributes
std::shared_ptr< SerialPort > serialPort
Constructor & Destructor Documentation
Bed::Bed ()
Bed Default bed constructor.
References serialPort.
Bed::~Bed () virtual
References serialPort.
Member Function Documentation
void Bed::command (const char relay, bool on)
command
Takes a relay number from 0 to 7 and respose with the byte code to write to serial port. an on or off boolean value is given in order to give the appropriate code to turn the relay on or off
Parameters
relay
on
Returns
References relay, and serialPort.
Referenced by Raspbed::bedDownHoldButton(), Raspbed::bedUpHoldButton(), Raspbed::feetDownHoldButton(), Raspbed::feetUpHoldButton(), Raspbed::headDownHoldButton(), Raspbed::headUpHoldButton(), Raspbed::lowerWheelsHoldButton(), Raspbed::on_bedDownButton_pressed(), Raspbed::on_bedDownButton_released(), Raspbed::on_bedUpButton_pressed(), Raspbed::on_bedUpButton_released(), Raspbed::on_feetDownButton_pressed(), Raspbed::on_feetDownButton_released(), Raspbed::on_feetUpButton_pressed(), Raspbed::on_feetUpButton_released(), Raspbed::on_flattenBedButton_clicked(), Raspbed::on_headDownButton_pressed(), Raspbed::on_headDownButton_released(), Raspbed::on_headUpButton_pressed(), Raspbed::on_headUpButton_released(), Raspbed::on_lowerWheelsButton_pressed(), Raspbed::on_lowerWheelsButton_released(), Raspbed::on_trendButton_pressed(), Raspbed::on_trendButton_released(), and Raspbed::trendHoldButton().
std::shared_ptr< SerialPort > Bed::getSerialPort ()
References serialPort.
Referenced by Raspbed::eventFilter(), Raspbed::mousePressEvent(), Raspbed::openSettings(), Raspbed::resetBed(), and Raspbed::setupButtons().
Member Data Documentation
struct Bed::Relay Bed::relay
Referenced by Raspbed::bedDownHoldButton(), Raspbed::bedUpHoldButton(), command(), Raspbed::feetDownHoldButton(), Raspbed::feetUpHoldButton(), Raspbed::headDownHoldButton(), Raspbed::headUpHoldButton(), Raspbed::lowerWheelsHoldButton(), Raspbed::on_bedDownButton_pressed(), Raspbed::on_bedDownButton_released(), Raspbed::on_bedUpButton_pressed(), Raspbed::on_bedUpButton_released(), Raspbed::on_feetDownButton_pressed(), Raspbed::on_feetDownButton_released(), Raspbed::on_feetUpButton_pressed(), Raspbed::on_feetUpButton_released(), Raspbed::on_flattenBedButton_clicked(), Raspbed::on_headDownButton_pressed(), Raspbed::on_headDownButton_released(), Raspbed::on_headUpButton_pressed(), Raspbed::on_headUpButton_released(), Raspbed::on_lowerWheelsButton_pressed(), Raspbed::on_lowerWheelsButton_released(), Raspbed::on_trendButton_pressed(), Raspbed::on_trendButton_released(), and Raspbed::trendHoldButton().
std::shared_ptr<SerialPort> Bed::serialPort private
Referenced by Bed(), command(), getSerialPort(), and ~Bed().
The documentation for this class was generated from the following files:
/home/john/workspace/Raspbed/QRaspbed/Bed.hpp
/home/john/workspace/Raspbed/QRaspbed/Bed.cpp