QRaspbed: Raspbed Class Reference
Raspbed Class Reference
The Raspbed class. Holds Main window gui logic.
#include <Raspbed.hpp>
Public Member Functions
Raspbed (QWidget *parent=0)
Raspbed constructor. Loads settings from a Data object, set's up display, and settingsmenu.
~Raspbed ()
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event)
Event filter for window. Only applied if not in button mode.
Private Slots
void on_headUpButton_pressed ()
Slot called upon press of head up button. Causes a call to write the signal to the relay to raise head of bed.
void on_headUpButton_released ()
Slot called upon release of head down button. Causes a call to write a signal to the relay to stop the raising of the head of the bed.
void on_headDownButton_pressed ()
Slot called upon press of head down button. Causes a call to write the signal to the relay to lower the head of bed.
void on_headDownButton_released ()
Slot called upon release of head down button. Causes a call to write a signal to the relay to stop the lowering of the head of the bed.
void on_feetUpButton_pressed ()
Slot called upon press of feet up button. Causes a call to write the signal to the relay to raise the feet of bed.
void on_feetUpButton_released ()
Slot called upon release of feet up button. Causes a call to write a signal to the relay to stop the raising of the feet of the bed.
void on_feetDownButton_pressed ()
Slot called upon press of feet down button. Causes a call to write the signal to the relay to lower the feet of the bed.
void on_feetDownButton_released ()
Slot called upon release of feet down button. Causes a call to write a signal to the relay to stop the lowering of the feet of the bed.
void on_trendButton_pressed ()
Slot called upon press of the trend button. Causes a call to write the signal to the relay to trend the bed.
void on_trendButton_released ()
Slot called upon release of trend button. Causes a call to write a signal to the relay to stop the trending of the bed.
void on_bedUpButton_pressed ()
Slot called upon press of bed up button. Causes a call to write the signal to the relay to raise the bed.
void on_bedUpButton_released ()
Slot called upon release of bed up button. Causes a call to write a signal to the relay to stop the raising of the bed.
void on_bedDownButton_pressed ()
Slot called upon press of bed down button. Causes a call to write the signal to the relay to lower the bed.
void on_bedDownButton_released ()
Slot called upon release of bed down button. Causes a call to write a signal to the relay to stop the lowering of the bed.
void on_lowerWheelsButton_pressed ()
Slot called upon press of the lower wheels button. Causes a call to write the signal to the relay to lower the bed and press the wheels button at the same time.
void on_lowerWheelsButton_released ()
Slot called upon release of lower wheels button. Causes a call to write a signal to the relay to stop the lowering the bed and pressing the wheels button at the same time.
void on_flattenBedButton_clicked ()
Slot called upon pressing the flatten bed button. It writes writes a signal to the relay to lower the feet and bed for 20 seconds, then writes a signal to close the relays.
void on_callButton_clicked ()
Slot called upon press of call button. Sends a command to skype to call designated skype contact.
void openSettings ()
Slot called on press of settings button. Opens a settings dialog. Loops thru all serial port devices and adds them to a list.Loads the different settings variables from the settings class and sets them into the dialog. If the dialog is accepted the settings are saved into the settings class and the display and bed are reloaded.
void resetClicks ()
resetClicks Resets numRightClicks and numLeftClicks to 0
Private Member Functions
void setupDisplay ()
setupDisplay sets up the icons by loading the pixmaps into the icons sets them to enabled or disabled depending on settings and sets the styling depending on button mode.
void setupIconBorders ()
setupIconBorders sets the icons images to bordered or nonbordered depending on settings.
void setupButtons ()
setupButtons sets up the icons size and other settings weather or not they are enabled as well as setting the proper event filter depending on the button mode.
void resetBed ()
resetBed stops the serial port and resets the port to current port from settings
QPushButton * nextButton ()
nextButton finds the next button selected when in sip'n puff mode
bool eventFilter (QObject *object, QEvent *event)
Event filter for buttons. Only applied if not in button mode.
void mouseSelectEvent (QMouseEvent *event)
Raspbed::mouseEvent.
void lowerWheelsHoldButton ()
command to hold down lower wheels button for the amount of time set in settings
void bedDownHoldButton ()
command to hold down bed down button for the amount of time set in settings
void bedUpHoldButton ()
command to hold down bed up button for the amount of time set in settings
void trendHoldButton ()
command to hold down trend button for the amount of time set in settings
void feetDownHoldButton ()
command to hold down feet down button for the amount of time set in settings
void feetUpHoldButton ()
command to hold down feet up button for the amount of time set in settings
void headUpHoldButton ()
command to hold down head up button for the amount of time set in settings
void headDownHoldButton ()
command to hold down head down button for the amount of time set in settings
Private Attributes
Data settings
Static settings class containing all of our settings variables.
QMenu * settingsMenu
settingsMenu menu bar button on tool bar
QAction * settingsAction
settingsAction is our signal that is triggered upon selecting settings in the tool bar menu.
Ui::Raspbed * ui
object pointing to our user interface
Bed bed
Class containing bed specific variables and commands.
QPixmap headUpPixmap
headUpPixmap head up icon
QPixmap headDownPixmap
headDownPixmap head down icon
QPixmap feetUpPixmap
feetUpPixmap feet up icon
QPixmap feetDownPixmap
feetDownPixmap feet down icon
QPixmap trendPixmap
trendPixmap trend icon
QPixmap bedUpPixmap
bedUpPixmap bed up icon
QPixmap bedDownPixmap
bedDownPixmap bed down icon
QPixmap lowerWheelsPixmap
lowerWheelsPixmap lower wheels icon
QPixmap flattenBedPixmap
flattenBedPixmap flatten bed icon
QPixmap callPixmap
callPixmap call bell icon
QPushButton * selectedButton
selectedButton is the currently selected button when in sip'n puff mode
bool selected
selected is true when a button is selected
int numRightClicks
number of right clicks that have occured since last time clicks were reset
int numLeftClicks
number of left clicks that have occured since last time clicks were reset
Detailed Description
The Raspbed class. Holds Main window gui logic.
Constructor & Destructor Documentation
Raspbed::Raspbed (QWidget * parent = 0) explicit
Raspbed constructor. Loads settings from a Data object, set's up display, and settingsmenu.
Parameters
parent
References Data::loadSettings(), numLeftClicks, numRightClicks, openSettings(), selected, selectedButton, settings, settingsAction, settingsMenu, setupDisplay(), and ui.
Raspbed::~Raspbed ()
References ui.
Member Function Documentation
void Raspbed::bedDownHoldButton () private
command to hold down bed down button for the amount of time set in settings
References bed, Bed::Relay::bed_down, Bed::command(), Data::getButtonHoldTime(), Bed::relay, and settings.
Referenced by mouseSelectEvent().
void Raspbed::bedUpHoldButton () private
command to hold down bed up button for the amount of time set in settings
References bed, Bed::Relay::bed_up, Bed::command(), Data::getButtonHoldTime(), Bed::relay, and settings.
Referenced by mouseSelectEvent().
bool Raspbed::eventFilter (QObject * object, QEvent * event) private
Event filter for buttons. Only applied if not in button mode.
Parameters
object pointer to the object on which the event occur.
event pointer to the event.
Returns
A boolean value of true if we reenterpreted the event, else we return QWidget::eventFilter(object, event);
References bed, Bed::getSerialPort(), Data::isButtonMode(), mouseSelectEvent(), and settings.
void Raspbed::feetDownHoldButton () private
command to hold down feet down button for the amount of time set in settings
References bed, Bed::command(), Bed::Relay::feet_down, Data::getButtonHoldTime(), Bed::relay, and settings.
Referenced by mouseSelectEvent().
void Raspbed::feetUpHoldButton () private
command to hold down feet up button for the amount of time set in settings
References bed, Bed::command(), Bed::Relay::feet_up, Data::getButtonHoldTime(), Bed::relay, and settings.
Referenced by mouseSelectEvent().
void Raspbed::headDownHoldButton () private
command to hold down head down button for the amount of time set in settings
References bed, Bed::command(), Data::getButtonHoldTime(), Bed::Relay::head_down, Bed::relay, and settings.
Referenced by mouseSelectEvent().
void Raspbed::headUpHoldButton () private
command to hold down head up button for the amount of time set in settings
References bed, Bed::command(), Data::getButtonHoldTime(), Bed::Relay::head_up, Bed::relay, and settings.
Referenced by mouseSelectEvent().
void Raspbed::lowerWheelsHoldButton () private
command to hold down lower wheels button for the amount of time set in settings
References bed, Bed::Relay::bed_down, Bed::command(), Data::getButtonHoldTime(), Bed::Relay::lower_wheels, Bed::relay, and settings.
Referenced by mouseSelectEvent().
void Raspbed::mousePressEvent (QMouseEvent * event) protected virtual
Event filter for window. Only applied if not in button mode.
Parameters
event pointer to the event.
References bed, Bed::getSerialPort(), Data::isButtonMode(), mouseSelectEvent(), and settings.
void Raspbed::mouseSelectEvent (QMouseEvent * event) private
Raspbed::mouseEvent.
Common method called for button and window events when not in buttonmode.
Parameters
event
References bedDownHoldButton(), bedUpHoldButton(), feetDownHoldButton(), feetUpHoldButton(), headDownHoldButton(), headUpHoldButton(), lowerWheelsHoldButton(), nextButton(), numLeftClicks, numRightClicks, on_callButton_clicked(), resetClicks(), selected, selectedButton, trendHoldButton(), and ui.
Referenced by eventFilter(), and mousePressEvent().
QPushButton * Raspbed::nextButton () private
nextButton finds the next button selected when in sip'n puff mode
Raspbed::nextButton.
Returns
A QPushButton pointer to the next button.
References selectedButton, and ui.
Referenced by mouseSelectEvent().
void Raspbed::on_bedDownButton_pressed () private slot
Slot called upon press of bed down button. Causes a call to write the signal to the relay to lower the bed.
References bed, Bed::Relay::bed_down, Bed::command(), Bed::relay, and ui.
void Raspbed::on_bedDownButton_released () private slot
Slot called upon release of bed down button. Causes a call to write a signal to the relay to stop the lowering of the bed.
References bed, Bed::Relay::bed_down, Bed::command(), Bed::relay, and ui.
void Raspbed::on_bedUpButton_pressed () private slot
Slot called upon press of bed up button. Causes a call to write the signal to the relay to raise the bed.
References bed, Bed::Relay::bed_up, Bed::command(), Bed::relay, and ui.
void Raspbed::on_bedUpButton_released () private slot
Slot called upon release of bed up button. Causes a call to write a signal to the relay to stop the raising of the bed.
References bed, Bed::Relay::bed_up, Bed::command(), Bed::relay, and ui.
void Raspbed::on_callButton_clicked () private slot
Slot called upon press of call button. Sends a command to skype to call designated skype contact.
References Data::getContact(), settings, and ui.
Referenced by mouseSelectEvent().
void Raspbed::on_feetDownButton_pressed () private slot
Slot called upon press of feet down button. Causes a call to write the signal to the relay to lower the feet of the bed.
References bed, Bed::command(), Bed::Relay::feet_down, Bed::relay, and ui.
void Raspbed::on_feetDownButton_released () private slot
Slot called upon release of feet down button. Causes a call to write a signal to the relay to stop the lowering of the feet of the bed.
References bed, Bed::command(), Bed::Relay::feet_down, Bed::relay, and ui.
void Raspbed::on_feetUpButton_pressed () private slot
Slot called upon press of feet up button. Causes a call to write the signal to the relay to raise the feet of bed.
References bed, Bed::command(), Bed::Relay::feet_up, Bed::relay, and ui.
void Raspbed::on_feetUpButton_released () private slot
Slot called upon release of feet up button. Causes a call to write a signal to the relay to stop the raising of the feet of the bed.
References bed, Bed::command(), Bed::Relay::feet_up, Bed::relay, and ui.
void Raspbed::on_flattenBedButton_clicked () private slot
Slot called upon pressing the flatten bed button. It writes writes a signal to the relay to lower the feet and bed for 20 seconds, then writes a signal to close the relays.
References bed, Bed::command(), Bed::Relay::feet_down, Bed::Relay::head_down, Bed::relay, and ui.
void Raspbed::on_headDownButton_pressed () private slot
Slot called upon press of head down button. Causes a call to write the signal to the relay to lower the head of bed.
References bed, Bed::command(), Bed::Relay::head_down, Bed::relay, and ui.
void Raspbed::on_headDownButton_released () private slot
Slot called upon release of head down button. Causes a call to write a signal to the relay to stop the lowering of the head of the bed.
References bed, Bed::command(), Bed::Relay::head_down, Bed::relay, and ui.
void Raspbed::on_headUpButton_pressed () private slot
Slot called upon press of head up button. Causes a call to write the signal to the relay to raise head of bed.
References bed, Bed::command(), Bed::Relay::head_up, Bed::relay, and ui.
void Raspbed::on_headUpButton_released () private slot
Slot called upon release of head down button. Causes a call to write a signal to the relay to stop the raising of the head of the bed.
References bed, Bed::command(), Bed::Relay::head_up, Bed::relay, and ui.
void Raspbed::on_lowerWheelsButton_pressed () private slot
Slot called upon press of the lower wheels button. Causes a call to write the signal to the relay to lower the bed and press the wheels button at the same time.
References bed, Bed::Relay::bed_down, Bed::command(), Bed::Relay::lower_wheels, Bed::relay, and ui.
void Raspbed::on_lowerWheelsButton_released () private slot
Slot called upon release of lower wheels button. Causes a call to write a signal to the relay to stop the lowering the bed and pressing the wheels button at the same time.
References bed, Bed::Relay::bed_down, Bed::command(), Bed::Relay::lower_wheels, Bed::relay, and ui.
void Raspbed::on_trendButton_pressed () private slot
Slot called upon press of the trend button. Causes a call to write the signal to the relay to trend the bed.
References bed, Bed::command(), Bed::relay, Bed::Relay::trend_up, and ui.
void Raspbed::on_trendButton_released () private slot
Slot called upon release of trend button. Causes a call to write a signal to the relay to stop the trending of the bed.
References bed, Bed::command(), Bed::relay, Bed::Relay::trend_up, and ui.
void Raspbed::openSettings () private slot
Slot called on press of settings button. Opens a settings dialog. Loops thru all serial port devices and adds them to a list.Loads the different settings variables from the settings class and sets them into the dialog. If the dialog is accepted the settings are saved into the settings class and the display and bed are reloaded.
Raspbed::openSettings.
References bed, Data::getButtonHoldTime(), Data::getContact(), Data::getPort(), Bed::getSerialPort(), Data::isBordered(), Data::isButtonMode(), resetBed(), Data::saveSettings(), Data::setBordered(), Data::setButtonHoldTime(), Data::setButtonMode(), Data::setContact(), Data::setPort(), settings, and setupDisplay().
Referenced by Raspbed().
void Raspbed::resetBed () private
resetBed stops the serial port and resets the port to current port from settings
References bed, Data::getPort(), Bed::getSerialPort(), settings, setupButtons(), and ui.
Referenced by openSettings().
void Raspbed::resetClicks () private slot
resetClicks Resets numRightClicks and numLeftClicks to 0
References numLeftClicks, and numRightClicks.
Referenced by mouseSelectEvent().
void Raspbed::setupButtons () private
setupButtons sets up the icons size and other settings weather or not they are enabled as well as setting the proper event filter depending on the button mode.
References bed, Bed::getSerialPort(), headUpPixmap, Data::isButtonMode(), settings, and ui.
Referenced by resetBed(), and setupDisplay().
void Raspbed::setupDisplay () private
setupDisplay sets up the icons by loading the pixmaps into the icons sets them to enabled or disabled depending on settings and sets the styling depending on button mode.
References bedDownPixmap, bedUpPixmap, callPixmap, feetDownPixmap, feetUpPixmap, flattenBedPixmap, headDownPixmap, headUpPixmap, Data::isButtonMode(), lowerWheelsPixmap, selectedButton, settings, setupButtons(), setupIconBorders(), trendPixmap, and ui.
Referenced by openSettings(), and Raspbed().
void Raspbed::setupIconBorders () private
setupIconBorders sets the icons images to bordered or nonbordered depending on settings.
References bedDownPixmap, bedUpPixmap, callPixmap, feetDownPixmap, feetUpPixmap, flattenBedPixmap, headDownPixmap, headUpPixmap, Data::isBordered(), lowerWheelsPixmap, settings, and trendPixmap.
Referenced by setupDisplay().
void Raspbed::trendHoldButton () private
command to hold down trend button for the amount of time set in settings
References bed, Bed::command(), Data::getButtonHoldTime(), Bed::relay, settings, and Bed::Relay::trend_up.
Referenced by mouseSelectEvent().
Member Data Documentation
Bed Raspbed::bed private
Class containing bed specific variables and commands.
Referenced by bedDownHoldButton(), bedUpHoldButton(), eventFilter(), feetDownHoldButton(), feetUpHoldButton(), headDownHoldButton(), headUpHoldButton(), lowerWheelsHoldButton(), mousePressEvent(), on_bedDownButton_pressed(), on_bedDownButton_released(), on_bedUpButton_pressed(), on_bedUpButton_released(), on_feetDownButton_pressed(), on_feetDownButton_released(), on_feetUpButton_pressed(), on_feetUpButton_released(), on_flattenBedButton_clicked(), on_headDownButton_pressed(), on_headDownButton_released(), on_headUpButton_pressed(), on_headUpButton_released(), on_lowerWheelsButton_pressed(), on_lowerWheelsButton_released(), on_trendButton_pressed(), on_trendButton_released(), openSettings(), resetBed(), setupButtons(), and trendHoldButton().
QPixmap Raspbed::bedDownPixmap private
bedDownPixmap bed down icon
Referenced by setupDisplay(), and setupIconBorders().
QPixmap Raspbed::bedUpPixmap private
bedUpPixmap bed up icon
Referenced by setupDisplay(), and setupIconBorders().
QPixmap Raspbed::callPixmap private
callPixmap call bell icon
Referenced by setupDisplay(), and setupIconBorders().
QPixmap Raspbed::feetDownPixmap private
feetDownPixmap feet down icon
Referenced by setupDisplay(), and setupIconBorders().
QPixmap Raspbed::feetUpPixmap private
feetUpPixmap feet up icon
Referenced by setupDisplay(), and setupIconBorders().
QPixmap Raspbed::flattenBedPixmap private
flattenBedPixmap flatten bed icon
Referenced by setupDisplay(), and setupIconBorders().
QPixmap Raspbed::headDownPixmap private
headDownPixmap head down icon
Referenced by setupDisplay(), and setupIconBorders().
QPixmap Raspbed::headUpPixmap private
headUpPixmap head up icon
Referenced by setupButtons(), setupDisplay(), and setupIconBorders().
QPixmap Raspbed::lowerWheelsPixmap private
lowerWheelsPixmap lower wheels icon
Referenced by setupDisplay(), and setupIconBorders().
int Raspbed::numLeftClicks private
number of left clicks that have occured since last time clicks were reset
Referenced by mouseSelectEvent(), Raspbed(), and resetClicks().
int Raspbed::numRightClicks private
number of right clicks that have occured since last time clicks were reset
Referenced by mouseSelectEvent(), Raspbed(), and resetClicks().
bool Raspbed::selected private
selected is true when a button is selected
Referenced by mouseSelectEvent(), and Raspbed().
QPushButton* Raspbed::selectedButton private
selectedButton is the currently selected button when in sip'n puff mode
Referenced by mouseSelectEvent(), nextButton(), Raspbed(), and setupDisplay().
Data Raspbed::settings private
Static settings class containing all of our settings variables.
Referenced by bedDownHoldButton(), bedUpHoldButton(), eventFilter(), feetDownHoldButton(), feetUpHoldButton(), headDownHoldButton(), headUpHoldButton(), lowerWheelsHoldButton(), mousePressEvent(), on_callButton_clicked(), openSettings(), Raspbed(), resetBed(), setupButtons(), setupDisplay(), setupIconBorders(), and trendHoldButton().
QAction* Raspbed::settingsAction private
settingsAction is our signal that is triggered upon selecting settings in the tool bar menu.
Referenced by Raspbed().
QMenu* Raspbed::settingsMenu private
settingsMenu menu bar button on tool bar
Referenced by Raspbed().
QPixmap Raspbed::trendPixmap private
trendPixmap trend icon
Referenced by setupDisplay(), and setupIconBorders().
Ui::Raspbed* Raspbed::ui private
object pointing to our user interface
Referenced by mouseSelectEvent(), nextButton(), on_bedDownButton_pressed(), on_bedDownButton_released(), on_bedUpButton_pressed(), on_bedUpButton_released(), on_callButton_clicked(), on_feetDownButton_pressed(), on_feetDownButton_released(), on_feetUpButton_pressed(), on_feetUpButton_released(), on_flattenBedButton_clicked(), on_headDownButton_pressed(), on_headDownButton_released(), on_headUpButton_pressed(), on_headUpButton_released(), on_lowerWheelsButton_pressed(), on_lowerWheelsButton_released(), on_trendButton_pressed(), on_trendButton_released(), Raspbed(), resetBed(), setupButtons(), setupDisplay(), and ~Raspbed().
The documentation for this class was generated from the following files:
/home/john/workspace/Raspbed/QRaspbed/Raspbed.hpp
/home/john/workspace/Raspbed/QRaspbed/Raspbed.cpp