raspbed: SerialPort Class Reference
SerialPort Class Reference
The SerialPort class represents the logic used for the connection, writing and disconnecting to serial port.
#include <SerialPort.hpp>
Public Member Functions
SerialPort (std::string name="ttyUSB0")
SerialPort (std::string name, unsigned int baud_rate, boost::asio::serial_port_base::character_size character_size, boost::asio::serial_port_base::stop_bits stop_bits, boost::asio::serial_port_base::parity com_parity, boost::asio::serial_port_base::flow_control flow_control)
bool open ()
void stop ()
void write (const char *data)
void print ()
Prints all of set options.
void setFlowControl (boost::asio::serial_port_base::flow_control flowControl)
boost::asio::serial_port_base::flow_control getFlowControl () const
void setParity (boost::asio::serial_port_base::parity parity)
boost::asio::serial_port_base::parity getParity () const
void setStopBits (boost::asio::serial_port_base::stop_bits stopBits)
boost::asio::serial_port_base::stop_bits getStopBits () const
void setCharacterSize (boost::asio::serial_port_base::character_size characterSize)
boost::asio::serial_port_base::character_size getCharacterSize () const
void setBaudRate (boost::asio::serial_port_base::baud_rate baudRate)
boost::asio::serial_port_base::baud_rate getBaudRate () const
void setPortName (std::string portName)
std::string getPortName () const
bool isConnected ()
void setConnected (bool connected)
std::vector< std::string > getDevices ()
Returns all open serial devices by getting all devices in "/sys/class/tty" in cross referencing them with all the devices that have device drivers, if they do they're returned in a vector.
Private Member Functions
bool portExists (std::string port)
portExists
Private Attributes
bool connected
Represents weather or not the serail port is open and ready for writing.
std::string portName
The name of the serial port you wish to use, most likely ttyUSB0.
boost::asio::serial_port_base::baud_rate baudRate
Baudrate of serial device.
boost::asio::serial_port_base::character_size characterSize
Number of bits to send through serial port.
boost::asio::serial_port_base::stop_bits stopBits
Number of bits to be sent at end of write.
boost::asio::serial_port_base::parity parity
Represents weather error detection is use.
boost::asio::serial_port_base::flow_control flowControl
Used for hand shaking.
boost::asio::io_service io
io service object
boost::asio::serial_port port
Represents your serial port.
Detailed Description
The SerialPort class represents the logic used for the connection, writing and disconnecting to serial port.
Constructor & Destructor Documentation
SerialPort::SerialPort (std::string name = "ttyUSB0")
Constructor. Default constructor.Creates and opens a serial device.
Parameters
name serial device name, example "ttyUSB0"
SerialPort::SerialPort (std::string name, unsigned int baud_rate, boost::asio::serial_port_base::character_size character_size, boost::asio::serial_port_base::stop_bits stop_bits, boost::asio::serial_port_base::parity com_parity, boost::asio::serial_port_base::flow_control flow_control)
Constructor: Main constructor that takes serial port options Creates and opens a serial device.
Parameters
devname serial device name, example ttyUSB0"
baud_rate serial baud rate
opt_parity serial parity, default none
opt_csize serial character size, default 8bit
opt_flow serial flow control, default none
opt_stop serial stop bits, default 1
Exceptions
boost::system::system_error if cannot open the serial device
Member Function Documentation
boost::asio::serial_port_base::baud_rate SerialPort::getBaudRate () const
References baudRate.
Referenced by print().
boost::asio::serial_port_base::character_size SerialPort::getCharacterSize () const
References characterSize.
Referenced by print().
std::vector< std::string > SerialPort::getDevices ()
Returns all open serial devices by getting all devices in "/sys/class/tty" in cross referencing them with all the devices that have device drivers, if they do they're returned in a vector.
Returns
A vector of strings of all the different active serial ports
Referenced by portExists().
boost::asio::serial_port_base::flow_control SerialPort::getFlowControl () const
References flowControl.
Referenced by print().
boost::asio::serial_port_base::parity SerialPort::getParity () const
References parity.
Referenced by print().
std::string SerialPort::getPortName () const
References portName.
Referenced by print().
boost::asio::serial_port_base::stop_bits SerialPort::getStopBits () const
References stopBits.
Referenced by print().
bool SerialPort::isConnected ()
References connected.
bool SerialPort::open ()
Open serial port, and sets all options. Returns true if port was successfully open
References baudRate, characterSize, connected, flowControl, parity, port, portExists(), portName, and stopBits.
bool SerialPort::portExists (std::string port) private
portExists
Parameters
port Name of port to check for. Given in format "ttyUSB0"
Returns
Returns true if port exists
References getDevices().
Referenced by open().
void SerialPort::print ()
Prints all of set options.
References getBaudRate(), getCharacterSize(), getFlowControl(), getParity(), getPortName(), and getStopBits().
void SerialPort::setBaudRate (boost::asio::serial_port_base::baud_rate baudRate)
References baudRate.
void SerialPort::setCharacterSize (boost::asio::serial_port_base::character_size characterSize)
References characterSize.
void SerialPort::setConnected (bool connected)
References connected.
void SerialPort::setFlowControl (boost::asio::serial_port_base::flow_control flowControl)
References flowControl.
void SerialPort::setParity (boost::asio::serial_port_base::parity parity)
References parity.
void SerialPort::setPortName (std::string portName)
References portName.
void SerialPort::setStopBits (boost::asio::serial_port_base::stop_bits stopBits)
References stopBits.
void SerialPort::stop ()
Closes the port
References connected, io, and port.
void SerialPort::write (const char * data)
Write data to serial port. Returns immediately.
Parameters
data array of char to be sent through the serial device
size array size
References port.
Member Data Documentation
boost::asio::serial_port_base::baud_rate SerialPort::baudRate private
Baudrate of serial device.
Referenced by getBaudRate(), open(), and setBaudRate().
boost::asio::serial_port_base::character_size SerialPort::characterSize private
Number of bits to send through serial port.
Referenced by getCharacterSize(), open(), and setCharacterSize().
bool SerialPort::connected private
Represents weather or not the serail port is open and ready for writing.
Referenced by isConnected(), open(), setConnected(), and stop().
boost::asio::serial_port_base::flow_control SerialPort::flowControl private
Used for hand shaking.
Referenced by getFlowControl(), open(), and setFlowControl().
boost::asio::io_service SerialPort::io private
io service object
Referenced by stop().
boost::asio::serial_port_base::parity SerialPort::parity private
Represents weather error detection is use.
Referenced by getParity(), open(), and setParity().
boost::asio::serial_port SerialPort::port private
Represents your serial port.
Referenced by open(), stop(), and write().
std::string SerialPort::portName private
The name of the serial port you wish to use, most likely ttyUSB0.
Referenced by getPortName(), open(), and setPortName().
boost::asio::serial_port_base::stop_bits SerialPort::stopBits private
Number of bits to be sent at end of write.
Referenced by getStopBits(), open(), and setStopBits().
The documentation for this class was generated from the following files:
/home/john/workspace/Raspbed/raspbed/SerialPort.hpp
/home/john/workspace/Raspbed/raspbed/SerialPort.cpp