raspbed: Data Class Reference
Data Class Reference
The Data class contains all the settings data variables as well as the saving and loading of data that needs to persist between running the application.
#include <Data.hpp>
Public Member Functions
Data ()
Data consructor, sets the organization name and application name for the settings object. On some computers you may need to set permissions in QSettings file in order to make settings persist between runs.
Static Public Member Functions
static void loadSettings ()
loadSettings loads the settings for the port, icon borders, contact, button mode, button hold time and button highlight color
static void saveSettings ()
saveSettings sets the settings for the port, icon borders, contact, button mode, button hold time and button highlight color
static QString getContact ()
static void setContact (const QString &value)
static bool isButtonMode ()
static void setButtonMode (bool value)
static bool isBordered ()
static void setBordered (bool value)
static QString getPort ()
static void setPort (const QString &value)
static int getButtonHoldTime ()
static void setButtonHoldTime (int value)
static bool isDarkHighlight ()
static void setDarkHighlight (bool value)
Private Member Functions
Data (Data const &)=delete
Data & operator= (Data const &)=delete
Static Private Attributes
static QString contact
skype contact that is called with emergency button
static bool iconBorders
iconBorders when set true turns on the borders on the button icons
static QString port
Name of serial port in the format ttyUSB0.
static QSettings settings
QSettings object that is used to persist settings between runs, makes Raspbed folder containing settings file.
static bool buttonMode
When buttonMode is set the buttons are pressable for use with a mouse, ideally for use on desktop. When buttonmode is set off the buttons toggle through on right clicks and select a button with left clicks.
static int buttonHoldTime
The amount of time a command continues for after a button is pressed.
static bool darkHighlight
When set on the buttons are highlighted in black for use with white screen, when off the buttons are highlighted white.
Detailed Description
The Data class contains all the settings data variables as well as the saving and loading of data that needs to persist between running the application.
Constructor & Destructor Documentation
Data::Data ()
Data consructor, sets the organization name and application name for the settings object. On some computers you may need to set permissions in QSettings file in order to make settings persist between runs.
Data::Data (Data const &) private delete
Member Function Documentation
int Data::getButtonHoldTime () static
References buttonHoldTime.
Referenced by Raspbed::bedDownHoldButton(), Raspbed::bedUpHoldButton(), Raspbed::feetDownHoldButton(), Raspbed::feetUpHoldButton(), Raspbed::headDownHoldButton(), Raspbed::headUpHoldButton(), Raspbed::lowerWheelsHoldButton(), Raspbed::openSettings(), and Raspbed::trendHoldButton().
QString Data::getContact () static
References contact.
Referenced by Raspbed::on_callButton_clicked(), and Raspbed::openSettings().
QString Data::getPort () static
References port.
Referenced by Raspbed::openSettings(), Raspbed::resetBed(), and Raspbed::setupButtons().
bool Data::isBordered () static
References iconBorders.
Referenced by Raspbed::openSettings(), and Raspbed::setupIconBorders().
bool Data::isButtonMode () static
References buttonMode.
Referenced by Raspbed::eventFilter(), Raspbed::mousePressEvent(), Raspbed::openSettings(), Raspbed::setupButtons(), and Raspbed::setupDisplay().
bool Data::isDarkHighlight () static
References darkHighlight.
Referenced by Raspbed::mouseSelectEvent(), Raspbed::openSettings(), and Raspbed::setupDisplay().
void Data::loadSettings () static
loadSettings loads the settings for the port, icon borders, contact, button mode, button hold time and button highlight color
References buttonHoldTime, buttonMode, contact, darkHighlight, iconBorders, port, and settings.
Referenced by Raspbed::Raspbed().
Data& Data::operator= (Data const &) private delete
void Data::saveSettings () static
saveSettings sets the settings for the port, icon borders, contact, button mode, button hold time and button highlight color
References buttonHoldTime, buttonMode, contact, darkHighlight, iconBorders, port, and settings.
Referenced by Raspbed::openSettings().
void Data::setBordered (bool value) static
References iconBorders.
Referenced by Raspbed::openSettings().
void Data::setButtonHoldTime (int value) static
References buttonHoldTime.
Referenced by Raspbed::openSettings().
void Data::setButtonMode (bool value) static
References buttonMode.
Referenced by Raspbed::openSettings().
void Data::setContact (const QString & value) static
References contact.
Referenced by Raspbed::openSettings().
void Data::setDarkHighlight (bool value) static
References darkHighlight.
Referenced by Raspbed::openSettings().
void Data::setPort (const QString & value) static
References port.
Referenced by Raspbed::openSettings().
Member Data Documentation
int Data::buttonHoldTime static private
The amount of time a command continues for after a button is pressed.
Referenced by getButtonHoldTime(), loadSettings(), saveSettings(), and setButtonHoldTime().
bool Data::buttonMode static private
When buttonMode is set the buttons are pressable for use with a mouse, ideally for use on desktop. When buttonmode is set off the buttons toggle through on right clicks and select a button with left clicks.
Referenced by isButtonMode(), loadSettings(), saveSettings(), and setButtonMode().
QString Data::contact static private
skype contact that is called with emergency button
Referenced by getContact(), loadSettings(), saveSettings(), and setContact().
bool Data::darkHighlight static private
When set on the buttons are highlighted in black for use with white screen, when off the buttons are highlighted white.
Referenced by isDarkHighlight(), loadSettings(), saveSettings(), and setDarkHighlight().
bool Data::iconBorders static private
iconBorders when set true turns on the borders on the button icons
Referenced by isBordered(), loadSettings(), saveSettings(), and setBordered().
QString Data::port static private
Name of serial port in the format ttyUSB0.
Referenced by getPort(), loadSettings(), saveSettings(), and setPort().
QSettings Data::settings static private
QSettings object that is used to persist settings between runs, makes Raspbed folder containing settings file.
Referenced by loadSettings(), and saveSettings().
The documentation for this class was generated from the following files:
/home/john/workspace/Raspbed/raspbed/Data.hpp
/home/john/workspace/Raspbed/raspbed/Data.cpp